semi/src/main/webapp/WEB-INF/views/member/find.jsp
=> 아이디/비밀번호 찾기 페이지 생성

semi/src/main/java/com/kh/semi/dao/MemberDao.java
=> MemberDao 생성

semi/src/main/java/com/kh/semi/controller/MemberController.java
=> MemberController 생성

semi/src/main/webapp/WEB-INF/views/member/find.jsp, semi/src/main/webapp/WEB-INF/views/member/findResult.jsp
=> 아이디 찾기.jsp 생성

semi/src/main/java/com/kh/semi/controller/MemberController.java, semi/src/main/java/com/kh/semi/dao/MemberDao.java, semi/src/main/webapp/WEB-INF/views/member/join.jsp, semi/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
=> 회원가입 기능 구현

semi/src/main/java/com/kh/semi/controller/MemberRestController.java, semi/src/main/java/com/kh/semi/dao/MemberDao.java, semi/src/main/resources/static/js/find-address.js, semi/src/main/resources/static/js/member-join.js, semi/src/main/webapp/WEB-INF/views/member/join.jsp
=> 회원가입 비동기 통신 및 주소 API 추가

semi/pom.xml, semi/src/main/java/com/kh/semi/component/RandomComponent.java, semi/src/main/java/com/kh/semi/configuration/CustomEmailProperties.java, semi/src/main/java/com/kh/semi/configuration/EmailConfiguration.java, semi/src/main/java/com/kh/semi/controller/MemberController.java, semi/src/main/resources/application.properties, semi/src/main/webapp/WEB-INF/views/member/findPw.jsp, semi/src/main/webapp/WEB-INF/views/member/findPwResult.jsp
=> 아이디 찾기/비밀번호 찾기

semi/src/main/java/com/kh/semi/controller/MemberRestController.java, semi/src/main/java/com/kh/semi/dao/MemberDao.java, semi/src/main/resources/static/js/member-join.js, semi/src/main/webapp/WEB-INF/views/member/join.jsp, semi/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
=> 이메일 형식 및 중복검사 추가

semi/src/main/webapp/WEB-INF/views/member/editFinish.jsp
=> 개인정보 수정 완료페이지 수정

semi/src/main/java/com/kh/semi/configuration/CustomFileuploadProperties.java, semi/src/main/java/com/kh/semi/controller/AttachmentController.java, semi/src/main/java/com/kh/semi/controller/AttachmentRestController.java, semi/src/main/java/com/kh/semi/controller/RecommendContoller.java, semi/src/main/java/com/kh/semi/dao/AttachmentDao.java, semi/src/main/java/com/kh/semi/dao/RecommendDao.java, semi/src/main/java/com/kh/semi/dto/AttachmentDto.java, semi/src/main/java/com/kh/semi/dto/RecommendDto.java, semi/src/main/resources/application.properties, semi/src/main/webapp/WEB-INF/views/member/join.jsp, semi/src/main/webapp/WEB-INF/views/recommend/detail.jsp, semi/src/main/webapp/WEB-INF/views/recommend/write.jsp, semi/src/main/webapp/WEB-INF/views/recommend/writeFinish.jsp
=> 추천 게시판 글쓰기 구현

semi/src/main/java/com/kh/semi/controller/QnaController.java, semi/src/main/java/com/kh/semi/dao/QnaDao.java, semi/src/main/java/com/kh/semi/service/QnaService.java, semi/src/main/webapp/WEB-INF/views/qna/edit.jsp
=> Q&A 게시판 수정 기능 추가/작성 문제 해결

semi/src/main/webapp/WEB-INF/views/member/login.jsp
=> 로그인 페이지 수정

semi/src/main/java/com/kh/semi/controller/RecommendContoller.java, semi/src/main/java/com/kh/semi/controller/RecommendRestController.java, semi/src/main/java/com/kh/semi/dao/RecommendDao.java, semi/src/main/java/com/kh/semi/dao/RecommendLikeDao.java, semi/src/main/java/com/kh/semi/dto/RecommendDto.java, semi/src/main/java/com/kh/semi/dto/RecommendLikeDto.java, semi/src/main/java/com/kh/semi/vo/RecommendLikeVO.java, semi/src/main/resources/static/js/recommend-like.js, semi/src/main/webapp/WEB-INF/views/recommend/detail.jsp
=> 추천 게시판 기능 추가 및 구현중

semi/src/main/java/com/kh/semi/controller/RecommendContoller.java, semi/src/main/webapp/WEB-INF/views/recommend/detail.jsp, semi/src/main/webapp/WEB-INF/views/recommend/list.jsp
=> 정말 삭제하시겠습니까 했음

semi/src/main/java/com/kh/semi/controller/MemberController.java, semi/src/main/java/com/kh/semi/dao/MemberProfileDao.java, semi/src/main/java/com/kh/semi/dto/MemberProfileDto.java, semi/src/main/java/com/kh/semi/service/MemberService.java, semi/src/main/resources/static/js/review-like.js, semi/src/main/webapp/WEB-INF/views/member/edit.jsp, semi/src/main/webapp/WEB-INF/views/member/join.jsp, semi/src/main/webapp/WEB-INF/views/member/mypage.jsp, semi/src/main/webapp/WEB-INF/views/review/detail.jsp
회원 정보 : 이미지 첨부 기능 추가
_마이페이지/개인정보 수정페이지/등록페이지
=> 회원 정보 : 이미지 첨부 기능 추가

semi/src/main/webapp/WEB-INF/views/home.jsp, semi/src/main/webapp/WEB-INF/views/template/header.jsp
=> 홈에 사진 누르면 링크로 가짐 ㅋㄷ

semi/src/main/java/com/kh/semi/controller/QnaController.java, semi/src/main/java/com/kh/semi/dao/QnaDao.java, semi/src/main/java/com/kh/semi/dto/QnaDto.java, semi/src/main/java/com/kh/semi/service/QnaService.java, semi/src/main/webapp/WEB-INF/views/qna/detail.jsp, semi/src/main/webapp/WEB-INF/views/qna/edit.jsp, semi/src/main/webapp/WEB-INF/views/qna/list.jsp, semi/src/main/webapp/WEB-INF/views/qna/write.jsp
=> 03/28 Q&A 게시판 추가 구현

semi/src/main/webapp/WEB-INF/views/qna/list.jsp, semi/src/main/webapp/WEB-INF/views/qna/write.jsp
=> 게시판 리스트 추가 몬가 수정

semi/src/main/resources/static/css/commons.css, semi/src/main/webapp/WEB-INF/views/template/header.jsp
=> 헤더바꾸고 css조금바꿈 ㅎ

semi/src/main/java/com/kh/semi/controller/ReviewController.java, semi/src/main/webapp/WEB-INF/views/review/detail.jsp
=> 후기 상세페이지 : 프로필 이미지 추가

semi/src/main/webapp/WEB-INF/views/member/edit.jsp
=> 개인정보 변경페이지 : 프로필 이미지 크기 수정

semi/src/main/java/com/kh/semi/vo/QnaPaginationVO.java, semi/src/main/resources/static/css/commons.css, semi/src/main/webapp/WEB-INF/views/qna/list.jsp, semi/src/main/webapp/WEB-INF/views/review/list.jsp
=> 게시판 디자인 수정

semi/src/main/resources/static/css/commons.css, semi/src/main/webapp/WEB-INF/views/member/edit.jsp, semi/src/main/webapp/WEB-INF/views/member/join.jsp, semi/src/main/webapp/WEB-INF/views/review/detail.jsp
=> 회원가입 페이지 : 프로필 미리보기 기능 추가

semi/src/main/java/com/kh/semi/controller/QnaController.java, semi/src/main/webapp/WEB-INF/views/member/mypage.jsp, semi/src/main/webapp/WEB-INF/views/member/passwordFinish.jsp, semi/src/main/webapp/WEB-INF/views/qna/detail.jsp, semi/src/main/webapp/WEB-INF/views/qna/edit.jsp, semi/src/main/webapp/WEB-INF/views/qna/list.jsp, semi/src/main/webapp/WEB-INF/views/qna/write.jsp
=> qna 게시판 여러가지 함

semi/src/main/java/com/kh/semi/configuration/InterceptorConfiguration.java, semi/src/main/java/com/kh/semi/controller/RecommendContoller.java, semi/src/main/java/com/kh/semi/interceptor/RecommendInterceptor.java, semi/src/main/resources/static/css/commons.css, semi/src/main/webapp/WEB-INF/views/recommend/detail.jsp, semi/src/main/webapp/WEB-INF/views/recommend/listTotal.jsp, semi/src/main/webapp/WEB-INF/views/review/listTotal.jsp, semi/src/main/webapp/WEB-INF/views/search.jsp, semi/src/main/webapp/WEB-INF/views/template/header.jsp
=> 통합 검색 기능 구현 및 수정

semi/src/main/java/com/kh/semi/controller/ReviewController.java, semi/src/main/java/com/kh/semi/dao/ReviewDao.java, semi/src/main/java/com/kh/semi/vo/ReviewPaginationVO2.java, semi/src/main/webapp/WEB-INF/views/review/listTotal.jsp, semi/src/main/webapp/WEB-INF/views/search.jsp
=> 통합 검색 구현 및 수정

semi/src/main/java/com/kh/semi/controller/QnaController.java, semi/src/main/webapp/WEB-INF/views/home.jsp, semi/src/main/webapp/WEB-INF/views/member/join.jsp, semi/src/main/webapp/WEB-INF/views/qna/list.jsp
=> 메인 화면 디자인 추가

semi/src/main/webapp/WEB-INF/views/home.jsp
=> 홈에 사진 갯수 6개로 바꿈

semi/src/main/java/com/kh/semi/controller/RecommendContoller.java, semi/src/main/java/com/kh/semi/dao/RecommendDao.java, semi/src/main/java/com/kh/semi/dto/RecommendAttachDto.java, semi/src/main/java/com/kh/semi/dto/RecommendDto.java, semi/src/main/resources/static/js/recommend-find-address.js, semi/src/main/resources/static/js/recommend-write.js, semi/src/main/webapp/WEB-INF/views/recommend/detail.jsp, semi/src/main/webapp/WEB-INF/views/recommend/edit.jsp, semi/src/main/webapp/WEB-INF/views/recommend/write.jsp, semi/src/main/webapp/WEB-INF/views/template/header.jsp
=> 추천 게시판 주소 및 지도 표시 추가

semi/src/main/webapp/WEB-INF/views/recommend/detail.jsp
=> 추천 게시판 지도 추가 및 길찾기 기능 추가

semi/src/main/webapp/WEB-INF/views/member/join.jsp
=> 회원 가입 프로필 이미지 디자인 변경 및 확장자 검사

semi/src/main/resources/static/js/review-reply.js, semi/src/main/webapp/WEB-INF/views/review/detail.jsp
=> 후기 게시판 관리자 댓글 삭제 기능 구현

semi/src/main/java/com/kh/semi/dao/QnaDao.java, semi/src/main/webapp/WEB-INF/views/qna/list.jsp
=> Q&A 게시판 작성자명으로 검색 기능 수정

semi/src/main/webapp/WEB-INF/views/home.jsp, semi/src/main/webapp/WEB-INF/views/recommend/detail.jsp
=> 카카오 key 수정

semi/src/main/java/com/kh/semi/controller/QnaController.java, semi/src/main/java/com/kh/semi/dao/QnaDao.java, semi/src/main/java/com/kh/semi/vo/QnaPaginationVO.java, semi/src/main/webapp/WEB-INF/views/qna/list.jsp, semi/src/main/webapp/WEB-INF/views/review/list.jsp
=> q&a 게시판 수정

semi/src/main/java/com/kh/semi/component/RandomComponent.java, semi/src/main/java/com/kh/semi/dao/QnaDao.java, semi/src/main/webapp/WEB-INF/views/member/edit.jsp, semi/src/main/webapp/WEB-INF/views/member/join.jsp
회원 가입, 마이 페이지 이미지 업로드 오류 수정 및 일회용 비밀번호 오류 수정
=> 회원 가입, 마이 페이지 이미지 업로드 오류 수정 및 일회용 비밀번호 오류 수정

semi/src/main/java/com/kh/semi/advice/ErrorController.java, semi/src/main/java/com/kh/semi/advice/RequireLoginException.java, semi/src/main/java/com/kh/semi/advice/RequirePermissionException.java, semi/src/main/webapp/WEB-INF/views/error/404.jsp, semi/src/main/webapp/WEB-INF/views/error/sorry.jsp
=> 오류페이지 만들어쪄욤

semi/src/main/java/com/kh/semi/controller/QnaController.java, semi/src/main/java/com/kh/semi/dao/QnaDao.java, semi/src/main/java/com/kh/semi/vo/QnaPaginationVO.java, semi/src/main/webapp/WEB-INF/views/qna/list.jsp
=> Q&A 페이지네이션 오류 해결

semi/src/main/webapp/WEB-INF/views/qna/detail.jsp
Q&A 상세 페이지 비로그인 시 글쓰기 버튼 안보이게 처리
=> Q&A 상세 페이지 비로그인 시 글쓰기 버튼 안보이게 처리

semi/src/main/java/com/kh/semi/dao/QnaDao.java
=> 공지사항 정렬 순서 수정
